// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wplrzrguchdfubxkiozi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwbHJ6cmd1Y2hkZnVieGtpb3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0ODk0ODAsImV4cCI6MjA2NzA2NTQ4MH0.34yuWv_bMSwalU_I5aunNHXj09qZpp1B1Wns8QYVJcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});